/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.29;

interface IRewardProcessor  {
    function calculateReward(uint256 amount, bool has_bonus, bool has_strict_bonus) external view returns (uint256);

    function updateMultiplyFactor(uint256 new_factor) external;

    function assertOwner() external view;

    error InvalidMultiplyFactor();

    error Unauthorized();

    error ZeroValue();
}